#https://www.tpisoftware.com/tpu/articleDetails/1826
version: "3.7"

services:

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manga_server
    command: gunicorn -b :5000 --threads 4 app:app --preload
    # restart: always
    environment:
      - FLASK_CONFIG=docker
    ports:
      - 9898:5000
    depends_on:
      - redis
      - db
    restart: always

  db:
    build:
      context: ./sqldata
      dockerfile: Dockerfile
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    #資料持久化與本機共享資料夾
    #volumes:
    #  - ./sqldata:/docker-entrypoint-initdb.d

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    command: celery -A app.celery_app worker --loglevel=info
    environment:
      - FLASK_CONFIG=docker
    volumes:
      - .:/usr/src/app
    depends_on:
        - flask
        - redis

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - 6379:6379