"""add likes

Revision ID: 5f5684cabf81
Revises: 9dee039c1e65
Create Date: 2022-06-10 16:00:33.934107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5684cabf81'
down_revision = '9dee039c1e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('insert_time', sa.DateTime(), nullable=True),
    sa.Column('insert_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mid'], ['manga.mid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
