"""add personal page

Revision ID: 9dee039c1e65
Revises: d6d3304da9b9
Create Date: 2022-06-10 15:12:12.488128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dee039c1e65'
down_revision = 'd6d3304da9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('insert_user', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_hash')
    op.drop_column('user', 'about_me')
    op.drop_column('manga', 'insert_user')
    # ### end Alembic commands ###
