name: Manga CD

# 觸發條件
on:
  workflow_run:
    workflows: [ Manga CI ]
    types:
      - completed

# 執行一項或多項任務
jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: Deployment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "manga-jason"
          heroku_email: "q5040842@gmail.com"